// Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

#ifndef CANGJIE_BASIC_MACROCALLDIAGINFO_H
#define CANGJIE_BASIC_MACROCALLDIAGINFO_H

#include <map>
#include <memory>
#include <string>

#include "cangjie/Basic/Position.h"

namespace Cangjie {

struct MacroCallDiagInfo {
    Position macroCallBegin; /**< Begin position of the macro call node. */
    Position macroCallEnd;   /**< End position of the macro call node. */

    Position identifierPos; /**< Position of the MacroCall's identifier. Generated by parser */
    std::string identifier; /**< Macro name: Moo. Generated by parser */

    std::string fullName; /**< Full name of the Macro Call: p1.Moo. Generated by parser */

    Position mcBegin; /**< Begin position of new source after macro expansion. */
    Position mcEnd;   /**< End position of new source after macro expansion. */

    bool isForLSP{false};             /**< Whether this macro call is for LSP. */
    bool isCurFile{false};            /**< Whether the macro expansion is in the current file. */
    bool isCustom{false};             /**< Indicates Custom Annotation. */
    mutable bool hasShownCode{false}; /**< Has shown the code that generated by macro once in diagnostics. */
    std::map<unsigned int, Position, std::greater<unsigned int>>
        new2macroCallPosMap; /**< Mapping between new position column and new source position after macro expansion. */
    std::map<unsigned int, Position, std::greater<unsigned int>>
        new2originPosMap; /**< Mapping between new position column and origin source position before macro expansion. */
    std::map<unsigned int, Position, std::greater<unsigned int>>
        originPosMap; /**< Mapping between hash of origin position and begin position of origin token before macro
                         expansion. */

    Position MapPos(const Position& pos, bool isLowerBound = false) const;

    // Custom annotation in the current source file and not produced by macro expansion.
    bool IsCustomAnnotation() const
    {
        return isCustom && isCurFile;
    }
};

} // namespace Cangjie

#endif // CANGJIE_BASIC_MACROCALLDIAGINFO_H
